### PR TITLE
Sync statePrograms copies

### PR DESCRIPTION
**Pull request by rswerve**
## Summary

Just noticed that we made some updates to the statePrograms file in app-api.  But we also have a copy of that file in app-web 🤦 .  This just brings app-web up to date.

### CODE REVIEW

**Comment by haworku** [comment]
😵‍💫 I forgot about that. cc: @macrael 

It feels... very likely this could happen again. We should adjust the import-programs script to change the files in both places.

**Review by haworku — APPROVED** [review]
Hard to tell whats going on with the diff - but spot checked a few.

**Comment by macrael** [comment]
Ohh! it’s indenting by 4 spaces instead of 2

**Comment by macrael** [comment]
@rswerve can you re-save both files as 2-spaces indented for now and then we can merge this to make sure we don’t break anything. We can do a cleanup afterwards

**Comment by rswerve** [comment]
> @rswerve can you re-save both files as 2-spaces indented for now and then we can merge this to make sure we don’t break anything? We can do a cleanup afterwards

This is being formatted by Prettier.  Do we want different indenting for json?  https://github.com/CMSgov/managed-care-review/blob/main/.prettierrc#L3

**Comment by macrael** [comment]
No you are probably right, we can switch over to 4 spaces. Should be a fix we can make to the generator program to make it output 4 spaces as well and get on the program.

**Pull request merged**
