### PR TITLE
Update unlock button copy

### PR DESCRIPTION
**Pull request by joshmfranklin**
## Summary
Update unlock button copy from "submit" to "unlock"
Screen Shot 2022-04-21 at 1 56 08 PM

### CODE REVIEW

**Review by macrael — APPROVED** [review]
I'm surprised this didn't break any tests

**Comment by rswerve** [comment]
> I'm surprised this didn't break any tests

Snapshot tests are underrated.  🙂

**Comment by haworku** [comment]
@macrael peeked at test and looks like we have a `aria-label` hard coded to "Submit" on our Modal.tsx  submit button. Since the aria label determines the accessible name, the test  did not fail because the name is unchanged. 

Probably that Modal component should have an `aria-label of `{onSubmitText || 'Submit'}`

**Comment by macrael** [comment]
@haworku Ah ha, that would explain it. I bet you are right we want to aria-label to match, or if we want the button title to be what a screen reader reads do we even need to set aria-label?

**Pull request merged**
