### PR TITLE
MR-2881: Add count text for filters

### PR DESCRIPTION
**Pull request by rswerve**
## Summary

We want to display a bit of text when users are using filters, so that they either see a total count of submissions, when no filters are applied, or a x of y count, when some are.  There should be no message when filters are applied but don't return anything.

#### Screenshots

image
image
image

#### Test cases covered

Added lines to existing filter tests to also check the text when we filter.

### CODE REVIEW

**Review by JasonLin0991 — APPROVED** [review]
Looks great!

**Comment by JasonLin0991** [comment]
@rswerve I take it all back, it's not looking good yet. When no submission are found it should display `Displaying 0 of 5 submissions`

Figma
Screenshot 2023-01-04 at 6 13 46 PM

**Review by JasonLin0991 — CHANGES_REQUESTED** [review]
@rswerve I take it all back, it's not looking good yet. When no submission are found it should display `Displaying 0 of 5 submissions`

Figma
Screenshot 2023-01-04 at 6 13 46 PM

**Comment by rswerve** [comment]
> @rswerve I take it all back, it's not looking good yet. When no submission are found it should display `Displaying 0 of 5 submissions`
> 
> 

Thanks, I'll fix that.

**Comment by rswerve** [comment]
> @rswerve I take it all back, it's not looking good yet. When no submission are found it should display `Displaying 0 of 5 submissions`
> 
> Figma 

Actually, we need to check with design.  This is in the AC for the ticket: `If submission list has been filtered to 0, then do not display this line and display the blank state design. `

**Comment by rswerve** [comment]
Got clarification from design and pushed up new changes @JasonLin0991

**Review by JasonLin0991 — APPROVED** [review]
💯. Thanks for double checking with design!

**Pull request merged**
